# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  branches:
    include:
      - dev
      - features/*

variables:
  solution: 'Feeader.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  NET_VERSION: '6.0.x'

jobs:
- job: build_windows
  displayName: Build Windows
  pool:
    vmImage: 'windows-2022'
  steps:
    - task: UseDotNet@2
      displayName: 'Install .NET SDK'
      inputs:
        packageType: 'sdk'
        version: '$(NET_VERSION)'
    - task: DotNetCoreCLI@2
      displayName: 'Install .Net MAUI Workload'
      inputs:
        command: 'custom'
        custom: 'workload'
        arguments: 'install maui'
    - task: VSBuild@1
      displayName: 'Build Feeader'
      inputs:
        solution: '$(solution)'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
        restoreNugetPackages: true
    - task: VSTest@2
      displayName: 'Run Unit Tests'
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
