// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Monbsoft.Feeader.Infrastructure.Data;

#nullable disable

namespace Monbsoft.Feeader.Infrastructure.Data.Migrations
{
    [DbContext(typeof(FeeaderDbContext))]
    [Migration("20220715182637_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Monbsoft.Feeader.Domain.Feed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Feeds");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5660e7b9-7555-4d3f-b863-df658440820b"),
                            Created = new DateTime(2022, 7, 15, 20, 26, 37, 77, DateTimeKind.Local).AddTicks(4041),
                            Name = "BBC News",
                            Updated = new DateTime(2022, 7, 15, 20, 26, 37, 80, DateTimeKind.Local).AddTicks(6513),
                            Url = "http://feeds.bbci.co.uk/news/world/rss.xml"
                        },
                        new
                        {
                            Id = new Guid("cbab58bb-fa24-46b9-b68d-ee25ddefb1a6"),
                            Created = new DateTime(2022, 7, 15, 20, 26, 37, 80, DateTimeKind.Local).AddTicks(8563),
                            Name = "The New York Times",
                            Updated = new DateTime(2022, 7, 15, 20, 26, 37, 80, DateTimeKind.Local).AddTicks(8574),
                            Url = "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/section/world/rss.xml"
                        },
                        new
                        {
                            Id = new Guid("bcb81fd8-ab1d-4874-af23-35513d3d673d"),
                            Created = new DateTime(2022, 7, 15, 20, 26, 37, 80, DateTimeKind.Local).AddTicks(8581),
                            Name = "CNN",
                            Updated = new DateTime(2022, 7, 15, 20, 26, 37, 80, DateTimeKind.Local).AddTicks(8582),
                            Url = "http://rss.cnn.com/rss/edition_world.rss"
                        },
                        new
                        {
                            Id = new Guid("5ebb45a0-5fff-49ac-a5d5-691e6314ce71"),
                            Created = new DateTime(2022, 7, 15, 20, 26, 37, 80, DateTimeKind.Local).AddTicks(8585),
                            Name = "CNBC",
                            Updated = new DateTime(2022, 7, 15, 20, 26, 37, 80, DateTimeKind.Local).AddTicks(8587),
                            Url = "https://www.cnbc.com/id/100727362/device/rss/rss.html"
                        },
                        new
                        {
                            Id = new Guid("71a2df8c-cb34-4203-b045-375695439b8b"),
                            Created = new DateTime(2022, 7, 15, 20, 26, 37, 80, DateTimeKind.Local).AddTicks(8590),
                            Name = "The Washington Post",
                            Updated = new DateTime(2022, 7, 15, 20, 26, 37, 80, DateTimeKind.Local).AddTicks(8591),
                            Url = "https://feeds.washingtonpost.com/rss/world"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
